In [3]:
import numpy as np

def parse_dbn(dbn_file):
    with open(dbn_file, 'r') as f:
        lines = f.readlines()
        # TODO: rewrite this method to handle multiple sequences and structures
        # Check if the file is in the correct format
        if len(lines) < 3:
            raise ValueError('The DBN file does not contain enough lines to return sequence and structure')
        sequence = lines[1].strip()  # Second line is the sequence
        structure = lines[2].strip()  # Third line is the dot-bracket notation
    return sequence, structure

def construct_secondary_structure_matrix(sequence, structure):
    N = len(sequence)
    matrix = np.zeros((N, N), dtype=int)
    
    # Stack to hold positions of '('
    stack = []
    
    for i, char in enumerate(structure):
        if char == '(':
            stack.append(i)
        elif char == ')':
            if stack:
                j = stack.pop()
                matrix[i][j] = 1
                matrix[j][i] = 1  # Symmetric pairing
    return matrix

# Example usage:
dbn_file = 'example.dbn'  # Replace with actual DBN file path
sequence, structure = parse_dbn(dbn_file)
matrix = construct_secondary_structure_matrix(sequence, structure)

print(matrix)

[[0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]]
